# Generated by Django 4.1.1 on 2022-10-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('passeword', models.CharField(max_length=20)),
            ],
        ),
    ]
