# Generated by Django 4.1.1 on 2022-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_questions_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
