# Generated by Django 4.1.1 on 2022-12-09 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_on', models.DateField(auto_now=True)),
                ('score', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjects')),
            ],
            options={
                'ordering': ['-attempted_on'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=50, null=True)),
                ('option1', models.CharField(max_length=10)),
                ('option2', models.CharField(max_length=10)),
                ('option3', models.CharField(blank=True, max_length=10, null=True)),
                ('option4', models.CharField(blank=True, max_length=10, null=True)),
                ('answer', models.CharField(max_length=1)),
                ('public', models.BooleanField(default=True)),
                ('key', models.CharField(blank=True, max_length=6, null=True)),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subjects')),
            ],
        ),
    ]
