# Generated by Django 4.1.1 on 2022-10-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_questions_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='key',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
